// Seed song library: public-domain hymns, metrical psalms and service music.
// Every text here was written (or translated) before 1929 and is in the public domain.
// Chinese (zh) text is supplied only where a long-established Simplified Chinese
// version is in common use; otherwise only a zh title (when the title is well known) or nothing.

import type { L10n, Song, SongCategory, Stanza } from '../../shared/types.ts';

export type SeedSong = Omit<Song, 'id' | 'notes' | 'ccli'> & { key: string };

/** Build a stanza from lines (joined with \n). */
function st(label: string, en: string[], zh?: string[]): Stanza {
  const text: L10n = { en: en.join('\n') };
  if (zh) text.zh = zh.join('\n');
  return { label, text };
}

interface SongInput {
  key: string;
  title: L10n;
  author: string | null;
  composer: string | null;
  tune: string | null;
  meter: string | null;
  year: number | null;
  category?: SongCategory;
  psalm?: number | null;
  tags: string[];
  stanzas: Stanza[];
  refrain_after_each?: boolean;
}

function song(s: SongInput): SeedSong {
  return {
    key: s.key,
    title: s.title,
    author: s.author,
    composer: s.composer,
    tune: s.tune,
    meter: s.meter,
    year: s.year,
    category: s.category ?? 'hymn',
    psalm: s.psalm ?? null,
    public_domain: true,
    copyright: null,
    tags: s.tags,
    stanzas: s.stanzas,
    refrain_after_each: s.refrain_after_each ?? false,
  };
}

export const SEED_SONGS: SeedSong[] = [
  // ------------------------------------------------------------ praise & adoration
  song({
    key: 'holy-holy-holy',
    title: { en: 'Holy, Holy, Holy! Lord God Almighty', zh: '圣哉，圣哉，圣哉' },
    author: 'Reginald Heber',
    composer: 'John B. Dykes',
    tune: 'NICAEA',
    meter: '11.12.12.10',
    year: 1826,
    tags: ['praise', 'trinity', 'opening', 'morning'],
    stanzas: [
      st('1', [
        'Holy, holy, holy! Lord God Almighty!',
        'Early in the morning our song shall rise to thee;',
        'Holy, holy, holy! merciful and mighty!',
        'God in three Persons, blessed Trinity!',
      ]),
      st('2', [
        'Holy, holy, holy! all the saints adore thee,',
        'Casting down their golden crowns around the glassy sea;',
        'Cherubim and seraphim falling down before thee,',
        'Who wert, and art, and evermore shalt be.',
      ]),
      st('3', [
        'Holy, holy, holy! though the darkness hide thee,',
        'Though the eye of sinful man thy glory may not see,',
        'Only thou art holy; there is none beside thee,',
        'Perfect in power, in love, and purity.',
      ]),
      st('4', [
        'Holy, holy, holy! Lord God Almighty!',
        'All thy works shall praise thy name, in earth, and sky, and sea;',
        'Holy, holy, holy! merciful and mighty!',
        'God in three Persons, blessed Trinity!',
      ]),
    ],
  }),

  song({
    key: 'a-mighty-fortress',
    title: { en: 'A Mighty Fortress Is Our God', zh: '坚固保障' },
    author: 'Martin Luther (1529); tr. Frederic H. Hedge (1853)',
    composer: 'Martin Luther',
    tune: 'EIN FESTE BURG',
    meter: '8.7.8.7.6.6.6.6.7',
    year: 1529,
    tags: ['praise', 'reformation', 'trust', 'psalm-46'],
    stanzas: [
      st('1', [
        'A mighty fortress is our God,',
        'A bulwark never failing;',
        'Our helper he, amid the flood',
        'Of mortal ills prevailing:',
        'For still our ancient foe',
        'Doth seek to work us woe;',
        'His craft and power are great,',
        'And, armed with cruel hate,',
        'On earth is not his equal.',
      ]),
      st('2', [
        'Did we in our own strength confide,',
        'Our striving would be losing;',
        'Were not the right man on our side,',
        "The man of God's own choosing:",
        'Dost ask who that may be?',
        'Christ Jesus, it is he;',
        'Lord Sabaoth his name,',
        'From age to age the same,',
        'And he must win the battle.',
      ]),
      st('3', [
        'And though this world, with devils filled,',
        'Should threaten to undo us,',
        'We will not fear, for God hath willed',
        'His truth to triumph through us:',
        'The prince of darkness grim,',
        'We tremble not for him;',
        'His rage we can endure,',
        'For lo, his doom is sure;',
        'One little word shall fell him.',
      ]),
      st('4', [
        'That word above all earthly powers,',
        'No thanks to them, abideth;',
        'The Spirit and the gifts are ours',
        'Through him who with us sideth:',
        'Let goods and kindred go,',
        'This mortal life also;',
        'The body they may kill:',
        "God's truth abideth still,",
        'His kingdom is for ever.',
      ]),
    ],
  }),

  song({
    key: 'all-hail-the-power',
    title: { en: "All Hail the Power of Jesus' Name" },
    author: 'Edward Perronet (1779); alt. John Rippon (1787)',
    composer: 'Oliver Holden',
    tune: 'CORONATION',
    meter: '8.6.8.6.8.6',
    year: 1779,
    tags: ['praise', 'christ', 'kingship', 'opening'],
    stanzas: [
      st('1', [
        "All hail the power of Jesus' name!",
        'Let angels prostrate fall;',
        'Bring forth the royal diadem,',
        'And crown him Lord of all.',
      ]),
      st('2', [
        "Ye chosen seed of Israel's race,",
        'Ye ransomed from the fall,',
        'Hail him who saves you by his grace,',
        'And crown him Lord of all.',
      ]),
      st('3', [
        "Sinners, whose love can ne'er forget",
        'The wormwood and the gall,',
        'Go, spread your trophies at his feet,',
        'And crown him Lord of all.',
      ]),
      st('4', [
        'Let every kindred, every tribe,',
        'On this terrestrial ball,',
        'To him all majesty ascribe,',
        'And crown him Lord of all.',
      ]),
      st('5', [
        'O that with yonder sacred throng',
        'We at his feet may fall!',
        "We'll join the everlasting song,",
        'And crown him Lord of all.',
      ]),
    ],
  }),

  song({
    key: 'praise-to-the-lord-the-almighty',
    title: { en: 'Praise to the Lord, the Almighty' },
    author: 'Joachim Neander (1680); tr. Catherine Winkworth (1863), alt.',
    composer: 'Stralsund Gesangbuch (1665)',
    tune: 'LOBE DEN HERREN',
    meter: '14.14.4.7.8',
    year: 1680,
    tags: ['praise', 'opening', 'creation', 'psalm-103'],
    stanzas: [
      st('1', [
        'Praise to the Lord, the Almighty, the King of creation!',
        'O my soul, praise him, for he is thy health and salvation!',
        'All ye who hear,',
        'Now to his temple draw near;',
        'Join me in glad adoration!',
      ]),
      st('2', [
        "Praise to the Lord, who o'er all things so wondrously reigneth,",
        'Shelters thee under his wings, yea, so gently sustaineth!',
        'Hast thou not seen',
        "How thy desires e'er have been",
        'Granted in what he ordaineth?',
      ]),
      st('3', [
        'Praise to the Lord, who doth prosper thy work and defend thee;',
        'Surely his goodness and mercy here daily attend thee.',
        'Ponder anew',
        'What the Almighty can do,',
        'If with his love he befriend thee.',
      ]),
      st('4', [
        'Praise to the Lord! O let all that is in me adore him!',
        'All that hath life and breath, come now with praises before him!',
        'Let the Amen',
        'Sound from his people again:',
        'Gladly for aye we adore him.',
      ]),
    ],
  }),

  song({
    key: 'now-thank-we-all-our-god',
    title: { en: 'Now Thank We All Our God' },
    author: 'Martin Rinkart (c. 1636); tr. Catherine Winkworth (1858)',
    composer: 'Johann Crüger',
    tune: 'NUN DANKET',
    meter: '6.7.6.7.6.6.6.6',
    year: 1636,
    tags: ['praise', 'thanksgiving', 'trinity', 'closing'],
    stanzas: [
      st('1', [
        'Now thank we all our God,',
        'With heart and hands and voices,',
        'Who wondrous things hath done,',
        'In whom his world rejoices;',
        "Who, from our mothers' arms,",
        'Hath blessed us on our way',
        'With countless gifts of love,',
        'And still is ours today.',
      ]),
      st('2', [
        'O may this bounteous God',
        'Through all our life be near us,',
        'With ever joyful hearts',
        'And blessed peace to cheer us;',
        'And keep us in his grace,',
        'And guide us when perplexed,',
        'And free us from all ills',
        'In this world and the next.',
      ]),
      st('3', [
        'All praise and thanks to God',
        'The Father now be given,',
        'The Son, and him who reigns',
        'With them in highest heaven,',
        'The one eternal God,',
        'Whom earth and heaven adore;',
        'For thus it was, is now,',
        'And shall be evermore.',
      ]),
    ],
  }),

  song({
    key: 'joyful-joyful-we-adore-thee',
    title: { en: 'Joyful, Joyful, We Adore Thee' },
    author: 'Henry van Dyke',
    composer: 'Ludwig van Beethoven; arr. Edward Hodges',
    tune: 'HYMN TO JOY',
    meter: '8.7.8.7 D',
    year: 1907,
    tags: ['praise', 'joy', 'creation', 'opening'],
    stanzas: [
      st('1', [
        'Joyful, joyful, we adore thee,',
        'God of glory, Lord of love;',
        'Hearts unfold like flowers before thee,',
        'Opening to the sun above.',
        'Melt the clouds of sin and sadness;',
        'Drive the dark of doubt away;',
        'Giver of immortal gladness,',
        'Fill us with the light of day!',
      ]),
      st('2', [
        'All thy works with joy surround thee,',
        'Earth and heaven reflect thy rays,',
        'Stars and angels sing around thee,',
        'Center of unbroken praise.',
        'Field and forest, vale and mountain,',
        'Flowery meadow, flashing sea,',
        'Chanting bird and flowing fountain',
        'Call us to rejoice in thee.',
      ]),
      st('3', [
        'Thou art giving and forgiving,',
        'Ever blessing, ever blest,',
        'Wellspring of the joy of living,',
        'Ocean depth of happy rest!',
        'Thou our Father, Christ our Brother,',
        'All who live in love are thine;',
        'Teach us how to love each other,',
        'Lift us to the joy divine.',
      ]),
      st('4', [
        'Mortals, join the happy chorus',
        'Which the morning stars began;',
        "Father love is reigning o'er us,",
        'Brother love binds man to man.',
        'Ever singing, march we onward,',
        'Victors in the midst of strife;',
        'Joyful music leads us sunward',
        'In the triumph song of life.',
      ]),
    ],
  }),

  song({
    key: 'o-worship-the-king',
    title: { en: 'O Worship the King' },
    author: 'Robert Grant',
    composer: 'attr. Johann Michael Haydn; arr. William Gardiner',
    tune: 'LYONS',
    meter: '10.10.11.11',
    year: 1833,
    tags: ['praise', 'creation', 'opening', 'psalm-104'],
    stanzas: [
      st('1', [
        'O worship the King, all glorious above,',
        'O gratefully sing his power and his love:',
        'Our Shield and Defender, the Ancient of Days,',
        'Pavilioned in splendor, and girded with praise.',
      ]),
      st('2', [
        'O tell of his might, O sing of his grace,',
        'Whose robe is the light, whose canopy space;',
        'His chariots of wrath the deep thunderclouds form,',
        'And dark is his path on the wings of the storm.',
      ]),
      st('3', [
        'The earth with its store of wonders untold,',
        'Almighty, thy power hath founded of old;',
        'Hath stablished it fast by a changeless decree,',
        'And round it hath cast, like a mantle, the sea.',
      ]),
      st('4', [
        'Thy bountiful care what tongue can recite?',
        'It breathes in the air, it shines in the light;',
        'It streams from the hills, it descends to the plain,',
        'And sweetly distils in the dew and the rain.',
      ]),
      st('5', [
        'Frail children of dust, and feeble as frail,',
        'In thee do we trust, nor find thee to fail;',
        'Thy mercies how tender, how firm to the end,',
        'Our Maker, Defender, Redeemer, and Friend.',
      ]),
      st('6', [
        'O measureless Might, ineffable Love,',
        'While angels delight to hymn thee above,',
        'Thy humbler creation, though feeble their lays,',
        'With true adoration shall sing to thy praise.',
      ]),
    ],
  }),

  song({
    key: 'immortal-invisible',
    title: { en: 'Immortal, Invisible, God Only Wise' },
    author: 'Walter Chalmers Smith',
    composer: 'Welsh melody',
    tune: 'ST. DENIO',
    meter: '11.11.11.11',
    year: 1867,
    tags: ['praise', 'attributes-of-god', 'opening'],
    stanzas: [
      st('1', [
        'Immortal, invisible, God only wise,',
        'In light inaccessible hid from our eyes,',
        'Most blessed, most glorious, the Ancient of Days,',
        'Almighty, victorious, thy great name we praise.',
      ]),
      st('2', [
        'Unresting, unhasting, and silent as light,',
        'Nor wanting, nor wasting, thou rulest in might;',
        'Thy justice like mountains high soaring above',
        'Thy clouds, which are fountains of goodness and love.',
      ]),
      st('3', [
        'To all, life thou givest, to both great and small;',
        'In all life thou livest, the true life of all;',
        'We blossom and flourish as leaves on the tree,',
        'And wither and perish, but naught changeth thee.',
      ]),
      st('4', [
        'Great Father of glory, pure Father of light,',
        'Thine angels adore thee, all veiling their sight;',
        'All praise we would render: O help us to see',
        "'Tis only the splendor of light hideth thee.",
      ]),
    ],
  }),

  song({
    key: 'crown-him-with-many-crowns',
    title: { en: 'Crown Him with Many Crowns' },
    author: 'Matthew Bridges (1851); Godfrey Thring (1874)',
    composer: 'George J. Elvey',
    tune: 'DIADEMATA',
    meter: '6.6.8.6 D',
    year: 1851,
    tags: ['praise', 'christ', 'kingship', 'ascension', 'easter'],
    stanzas: [
      st('1', [
        'Crown him with many crowns,',
        'The Lamb upon his throne;',
        'Hark! how the heavenly anthem drowns',
        'All music but its own:',
        'Awake, my soul, and sing',
        'Of him who died for thee,',
        'And hail him as thy matchless King',
        'Through all eternity.',
      ]),
      st('2', [
        'Crown him the Lord of love;',
        'Behold his hands and side,',
        'Rich wounds, yet visible above,',
        'In beauty glorified:',
        'No angel in the sky',
        'Can fully bear that sight,',
        'But downward bends his wondering eye',
        'At mysteries so bright.',
      ]),
      st('3', [
        'Crown him the Lord of life,',
        "Who triumphed o'er the grave,",
        'And rose victorious in the strife',
        'For those he came to save;',
        'His glories now we sing',
        'Who died, and rose on high,',
        'Who died eternal life to bring,',
        'And lives that death may die.',
      ]),
      st('4', [
        'Crown him the Lord of years,',
        'The Potentate of time,',
        'Creator of the rolling spheres,',
        'Ineffably sublime:',
        'All hail, Redeemer, hail!',
        'For thou hast died for me;',
        'Thy praise shall never, never fail',
        'Throughout eternity.',
      ]),
    ],
  }),

  song({
    key: 'the-churchs-one-foundation',
    title: { en: "The Church's One Foundation" },
    author: 'Samuel J. Stone',
    composer: 'Samuel S. Wesley',
    tune: 'AURELIA',
    meter: '7.6.7.6 D',
    year: 1866,
    tags: ['church', 'communion-of-saints', 'baptism', 'lords-supper'],
    stanzas: [
      st('1', [
        "The Church's one foundation",
        'Is Jesus Christ her Lord;',
        'She is his new creation',
        'By water and the word:',
        'From heaven he came and sought her',
        'To be his holy bride;',
        'With his own blood he bought her,',
        'And for her life he died.',
      ]),
      st('2', [
        'Elect from every nation,',
        "Yet one o'er all the earth,",
        'Her charter of salvation',
        'One Lord, one faith, one birth;',
        'One holy name she blesses,',
        'Partakes one holy food,',
        'And to one hope she presses,',
        'With every grace endued.',
      ]),
      st('3', [
        'Though with a scornful wonder',
        'Men see her sore oppressed,',
        'By schisms rent asunder,',
        'By heresies distressed:',
        'Yet saints their watch are keeping,',
        'Their cry goes up, “How long?”',
        'And soon the night of weeping',
        'Shall be the morn of song.',
      ]),
      st('4', [
        "'Mid toil and tribulation,",
        'And tumult of her war,',
        'She waits the consummation',
        'Of peace for evermore;',
        'Till with the vision glorious',
        'Her longing eyes are blest,',
        'And the great Church victorious',
        'Shall be the Church at rest.',
      ]),
      st('5', [
        'Yet she on earth hath union',
        'With God the Three in One,',
        'And mystic sweet communion',
        'With those whose rest is won:',
        'O happy ones and holy!',
        'Lord, give us grace that we,',
        'Like them, the meek and lowly,',
        'On high may dwell with thee.',
      ]),
    ],
  }),

  // ------------------------------------------------------------ grace, cross & assurance
  song({
    key: 'amazing-grace',
    title: { en: 'Amazing Grace', zh: '奇异恩典' },
    author: 'John Newton',
    composer: 'Virginia Harmony (1831); arr. Edwin O. Excell',
    tune: 'NEW BRITAIN',
    meter: '8.6.8.6',
    year: 1779,
    tags: ['grace', 'assurance', 'salvation', 'response'],
    stanzas: [
      st('1', [
        'Amazing grace! how sweet the sound',
        'That saved a wretch like me!',
        'I once was lost, but now am found,',
        'Was blind, but now I see.',
      ]),
      st('2', [
        "'Twas grace that taught my heart to fear,",
        'And grace my fears relieved;',
        'How precious did that grace appear',
        'The hour I first believed!',
      ]),
      st('3', [
        'Through many dangers, toils, and snares,',
        'I have already come;',
        "'Tis grace hath brought me safe thus far,",
        'And grace will lead me home.',
      ]),
      st('4', [
        'The Lord has promised good to me,',
        'His word my hope secures;',
        'He will my shield and portion be',
        'As long as life endures.',
      ]),
      st('5', [
        'Yes, when this flesh and heart shall fail,',
        'And mortal life shall cease,',
        'I shall possess, within the veil,',
        'A life of joy and peace.',
      ]),
      st('6', [
        'The earth shall soon dissolve like snow,',
        'The sun forbear to shine;',
        'But God, who called me here below,',
        'Will be for ever mine.',
      ]),
    ],
  }),

  song({
    key: 'come-thou-fount',
    title: { en: 'Come, Thou Fount of Every Blessing' },
    author: 'Robert Robinson',
    composer: "Wyeth's Repository of Sacred Music, Part Second (1813)",
    tune: 'NETTLETON',
    meter: '8.7.8.7 D',
    year: 1758,
    tags: ['grace', 'praise', 'sanctification', 'response'],
    stanzas: [
      st('1', [
        'Come, thou Fount of every blessing,',
        'Tune my heart to sing thy grace;',
        'Streams of mercy, never ceasing,',
        'Call for songs of loudest praise.',
        'Teach me some melodious sonnet,',
        'Sung by flaming tongues above;',
        "Praise the mount! I'm fixed upon it,",
        'Mount of thy redeeming love.',
      ]),
      st('2', [
        'Here I raise my Ebenezer;',
        "Hither by thy help I'm come;",
        'And I hope, by thy good pleasure,',
        'Safely to arrive at home.',
        'Jesus sought me when a stranger,',
        'Wandering from the fold of God;',
        'He, to rescue me from danger,',
        'Interposed his precious blood.',
      ]),
      st('3', [
        'O to grace how great a debtor',
        "Daily I'm constrained to be!",
        'Let thy goodness, like a fetter,',
        'Bind my wandering heart to thee:',
        'Prone to wander, Lord, I feel it,',
        'Prone to leave the God I love;',
        "Here's my heart, O take and seal it;",
        'Seal it for thy courts above.',
      ]),
    ],
  }),

  song({
    key: 'be-thou-my-vision',
    title: { en: 'Be Thou My Vision' },
    author: 'Irish (c. 8th cent.); tr. Mary E. Byrne (1905); versified Eleanor H. Hull (1912)',
    composer: 'Irish melody',
    tune: 'SLANE',
    meter: '10.10.10.10',
    year: 1912,
    tags: ['devotion', 'consecration', 'response', 'closing'],
    stanzas: [
      st('1', [
        'Be thou my vision, O Lord of my heart;',
        'Naught be all else to me, save that thou art:',
        'Thou my best thought, by day or by night,',
        'Waking or sleeping, thy presence my light.',
      ]),
      st('2', [
        'Be thou my wisdom, and thou my true word;',
        'I ever with thee, and thou with me, Lord;',
        'Thou my great Father, I thy true son;',
        'Thou in me dwelling, and I with thee one.',
      ]),
      st('3', [
        'Be thou my battle-shield, sword for the fight;',
        'Be thou my dignity, thou my delight;',
        "Thou my soul's shelter, thou my high tower:",
        'Raise thou me heavenward, O Power of my power.',
      ]),
      st('4', [
        "Riches I heed not, nor man's empty praise,",
        'Thou mine inheritance, now and always:',
        'Thou and thou only, first in my heart,',
        'High King of heaven, my treasure thou art.',
      ]),
      st('5', [
        'High King of heaven, my victory won,',
        "May I reach heaven's joys, O bright heaven's Sun!",
        'Heart of my own heart, whatever befall,',
        'Still be my vision, O Ruler of all.',
      ]),
    ],
  }),

  song({
    key: 'when-i-survey',
    title: { en: 'When I Survey the Wondrous Cross' },
    author: 'Isaac Watts',
    composer: 'Lowell Mason',
    tune: 'HAMBURG',
    meter: '8.8.8.8',
    year: 1707,
    tags: ['cross', 'passion', 'lords-supper', 'consecration', 'response'],
    stanzas: [
      st('1', [
        'When I survey the wondrous cross',
        'On which the Prince of glory died,',
        'My richest gain I count but loss,',
        'And pour contempt on all my pride.',
      ]),
      st('2', [
        'Forbid it, Lord, that I should boast,',
        'Save in the death of Christ my God:',
        'All the vain things that charm me most,',
        'I sacrifice them to his blood.',
      ]),
      st('3', [
        'See, from his head, his hands, his feet,',
        'Sorrow and love flow mingled down:',
        "Did e'er such love and sorrow meet,",
        'Or thorns compose so rich a crown?',
      ]),
      st('4', [
        'Were the whole realm of nature mine,',
        'That were a present far too small;',
        'Love so amazing, so divine,',
        'Demands my soul, my life, my all.',
      ]),
    ],
  }),

  song({
    key: 'rock-of-ages',
    title: { en: 'Rock of Ages, Cleft for Me', zh: '万古磐石' },
    author: 'Augustus M. Toplady',
    composer: 'Thomas Hastings',
    tune: 'TOPLADY',
    meter: '7.7.7.7.7.7',
    year: 1776,
    tags: ['grace', 'cross', 'confession', 'assurance', 'lords-supper'],
    stanzas: [
      st('1', [
        'Rock of Ages, cleft for me,',
        'Let me hide myself in thee;',
        'Let the water and the blood,',
        'From thy wounded side which flowed,',
        'Be of sin the double cure,',
        'Save from wrath and make me pure.',
      ]),
      st('2', [
        'Not the labors of my hands',
        "Can fulfil thy law's demands;",
        'Could my zeal no respite know,',
        'Could my tears for ever flow,',
        'All for sin could not atone;',
        'Thou must save, and thou alone.',
      ]),
      st('3', [
        'Nothing in my hand I bring,',
        'Simply to thy cross I cling;',
        'Naked, come to thee for dress;',
        'Helpless, look to thee for grace;',
        'Foul, I to the fountain fly;',
        'Wash me, Saviour, or I die.',
      ]),
      st('4', [
        'While I draw this fleeting breath,',
        'When mine eyes shall close in death,',
        'When I soar to worlds unknown,',
        'See thee on thy judgment throne,',
        'Rock of Ages, cleft for me,',
        'Let me hide myself in thee.',
      ]),
    ],
  }),

  song({
    key: 'it-is-well',
    title: { en: 'It Is Well with My Soul', zh: '我心灵得安宁' },
    author: 'Horatio G. Spafford',
    composer: 'Philip P. Bliss',
    tune: 'VILLE DU HAVRE',
    meter: '11.8.11.9 with refrain',
    year: 1873,
    refrain_after_each: true,
    tags: ['assurance', 'trust', 'comfort', 'response'],
    stanzas: [
      st('1', [
        'When peace, like a river, attendeth my way,',
        'When sorrows like sea billows roll;',
        'Whatever my lot, thou hast taught me to say,',
        'It is well, it is well with my soul.',
      ]),
      st('R', ['It is well with my soul,', 'It is well, it is well with my soul.']),
      st('2', [
        'Though Satan should buffet, though trials should come,',
        'Let this blest assurance control,',
        'That Christ has regarded my helpless estate,',
        'And hath shed his own blood for my soul.',
      ]),
      st('3', [
        'My sin, O the bliss of this glorious thought!',
        'My sin, not in part, but the whole,',
        'Is nailed to the cross, and I bear it no more:',
        'Praise the Lord, praise the Lord, O my soul!',
      ]),
      st('4', [
        'And, Lord, haste the day when my faith shall be sight,',
        'The clouds be rolled back as a scroll;',
        'The trump shall resound, and the Lord shall descend,',
        'Even so, it is well with my soul.',
      ]),
    ],
  }),

  song({
    key: 'jesus-paid-it-all',
    title: { en: 'Jesus Paid It All' },
    author: 'Elvina M. Hall',
    composer: 'John T. Grape',
    tune: 'ALL TO CHRIST',
    meter: '6.6.7.7 with refrain',
    year: 1865,
    refrain_after_each: true,
    tags: ['cross', 'grace', 'assurance', 'response'],
    stanzas: [
      st('1', [
        'I hear the Saviour say,',
        '“Thy strength indeed is small;',
        'Child of weakness, watch and pray,',
        'Find in me thine all in all.”',
      ]),
      st('R', [
        'Jesus paid it all,',
        'All to him I owe;',
        'Sin had left a crimson stain,',
        'He washed it white as snow.',
      ]),
      st('2', [
        'Lord, now indeed I find',
        'Thy power, and thine alone,',
        "Can change the leper's spots",
        'And melt the heart of stone.',
      ]),
      st('3', [
        'For nothing good have I',
        'Whereby thy grace to claim;',
        "I'll wash my garments white",
        "In the blood of Calvary's Lamb.",
      ]),
      st('4', [
        'And when, before the throne,',
        'I stand in him complete,',
        '“Jesus died my soul to save,”',
        'My lips shall still repeat.',
      ]),
    ],
  }),

  song({
    key: 'and-can-it-be',
    title: { en: 'And Can It Be' },
    author: 'Charles Wesley',
    composer: 'Thomas Campbell',
    tune: 'SAGINA',
    meter: '8.8.8.8.8.8 extended',
    year: 1738,
    tags: ['grace', 'cross', 'assurance', 'justification', 'response'],
    stanzas: [
      st('1', [
        'And can it be that I should gain',
        "An interest in the Saviour's blood?",
        'Died he for me, who caused his pain?',
        'For me, who him to death pursued?',
        'Amazing love! how can it be',
        'That thou, my God, shouldst die for me?',
      ]),
      st('2', [
        "'Tis mystery all! th' Immortal dies:",
        'Who can explore his strange design?',
        'In vain the firstborn seraph tries',
        'To sound the depths of love divine!',
        "'Tis mercy all! let earth adore,",
        'Let angel minds inquire no more.',
      ]),
      st('3', [
        "He left his Father's throne above,",
        'So free, so infinite his grace;',
        'Emptied himself of all but love,',
        "And bled for Adam's helpless race:",
        "'Tis mercy all, immense and free;",
        'For, O my God, it found out me!',
      ]),
      st('4', [
        'Long my imprisoned spirit lay',
        "Fast bound in sin and nature's night;",
        'Thine eye diffused a quickening ray,',
        'I woke, the dungeon flamed with light;',
        'My chains fell off, my heart was free;',
        'I rose, went forth, and followed thee.',
      ]),
      st('5', [
        'No condemnation now I dread;',
        'Jesus, and all in him, is mine!',
        'Alive in him, my living Head,',
        'And clothed in righteousness divine,',
        "Bold I approach th' eternal throne,",
        'And claim the crown, through Christ, my own.',
      ]),
    ],
  }),

  song({
    key: 'before-the-throne',
    title: { en: 'Before the Throne of God Above' },
    author: 'Charitie Lees Bancroft',
    composer: null,
    tune: null,
    meter: '8.8.8.8 D',
    year: 1863,
    tags: ['assurance', 'christ', 'intercession', 'justification', 'response'],
    stanzas: [
      st('1', [
        'Before the throne of God above',
        'I have a strong, a perfect plea:',
        'A great High Priest, whose name is Love,',
        'Who ever lives and pleads for me.',
        'My name is graven on his hands,',
        'My name is written on his heart;',
        'I know that while in heaven he stands',
        'No tongue can bid me thence depart.',
      ]),
      st('2', [
        'When Satan tempts me to despair,',
        'And tells me of the guilt within,',
        'Upward I look, and see him there',
        'Who made an end of all my sin.',
        'Because the sinless Saviour died,',
        'My sinful soul is counted free;',
        'For God, the Just, is satisfied',
        'To look on him and pardon me.',
      ]),
      st('3', [
        'Behold him there! the bleeding Lamb!',
        'My perfect, spotless Righteousness,',
        'The great unchangeable I AM,',
        'The King of glory and of grace!',
        'One with himself, I cannot die,',
        'My soul is purchased by his blood;',
        'My life is hid with Christ on high,',
        'With Christ, my Saviour and my God.',
      ]),
    ],
  }),

  song({
    key: 'man-of-sorrows',
    title: { en: 'Man of Sorrows! What a Name' },
    author: 'Philip P. Bliss',
    composer: 'Philip P. Bliss',
    tune: 'HALLELUJAH! WHAT A SAVIOR',
    meter: '7.7.7.8',
    year: 1875,
    tags: ['cross', 'passion', 'lords-supper', 'praise', 'second-coming'],
    stanzas: [
      st('1', [
        '“Man of Sorrows!” what a name',
        'For the Son of God, who came',
        'Ruined sinners to reclaim!',
        'Hallelujah! what a Saviour!',
      ]),
      st('2', [
        'Bearing shame and scoffing rude,',
        'In my place condemned he stood;',
        'Sealed my pardon with his blood:',
        'Hallelujah! what a Saviour!',
      ]),
      st('3', [
        'Guilty, vile, and helpless we;',
        'Spotless Lamb of God was he;',
        '“Full atonement!” can it be?',
        'Hallelujah! what a Saviour!',
      ]),
      st('4', [
        'Lifted up was he to die,',
        '“It is finished!” was his cry;',
        'Now in heaven exalted high:',
        'Hallelujah! what a Saviour!',
      ]),
      st('5', [
        'When he comes, our glorious King,',
        'All his ransomed home to bring,',
        'Then anew this song we’ll sing:',
        'Hallelujah! what a Saviour!',
      ]),
    ],
  }),

  // ------------------------------------------------------------ trust, pilgrimage & evening
  song({
    key: 'how-firm-a-foundation',
    title: { en: 'How Firm a Foundation' },
    author: '“K” in Rippon’s Selection of Hymns',
    composer: "Funk's Compilation of Genuine Church Music (1832)",
    tune: 'FOUNDATION',
    meter: '11.11.11.11',
    year: 1787,
    tags: ['assurance', 'trust', 'scripture', 'comfort'],
    stanzas: [
      st('1', [
        'How firm a foundation, ye saints of the Lord,',
        'Is laid for your faith in his excellent word!',
        'What more can he say than to you he hath said,',
        'To you who for refuge to Jesus have fled?',
      ]),
      st('2', [
        'Fear not, I am with thee, O be not dismayed,',
        'For I am thy God, and will still give thee aid;',
        "I'll strengthen thee, help thee, and cause thee to stand,",
        'Upheld by my gracious, omnipotent hand.',
      ]),
      st('3', [
        'When through the deep waters I call thee to go,',
        'The rivers of woe shall not thee overflow;',
        'For I will be with thee, thy troubles to bless,',
        'And sanctify to thee thy deepest distress.',
      ]),
      st('4', [
        'When through fiery trials thy pathway shall lie,',
        'My grace, all-sufficient, shall be thy supply;',
        'The flame shall not hurt thee; I only design',
        'Thy dross to consume, and thy gold to refine.',
      ]),
      st('5', [
        'The soul that on Jesus hath leaned for repose,',
        'I will not, I will not desert to his foes;',
        'That soul, though all hell should endeavor to shake,',
        "I'll never, no never, no never forsake.",
      ]),
    ],
  }),

  song({
    key: 'o-god-our-help',
    title: { en: 'O God, Our Help in Ages Past' },
    author: 'Isaac Watts',
    composer: 'William Croft',
    tune: 'ST. ANNE',
    meter: '8.6.8.6',
    year: 1719,
    psalm: 90,
    tags: ['trust', 'providence', 'new-year', 'funeral', 'psalm-90'],
    stanzas: [
      st('1', [
        'O God, our help in ages past,',
        'Our hope for years to come,',
        'Our shelter from the stormy blast,',
        'And our eternal home:',
      ]),
      st('2', [
        'Under the shadow of thy throne',
        'Thy saints have dwelt secure;',
        'Sufficient is thine arm alone,',
        'And our defence is sure.',
      ]),
      st('3', [
        'Before the hills in order stood,',
        'Or earth received her frame,',
        'From everlasting thou art God,',
        'To endless years the same.',
      ]),
      st('4', [
        'A thousand ages in thy sight',
        'Are like an evening gone;',
        'Short as the watch that ends the night',
        'Before the rising sun.',
      ]),
      st('5', [
        'Time, like an ever-rolling stream,',
        'Bears all its sons away;',
        'They fly, forgotten, as a dream',
        'Dies at the opening day.',
      ]),
      st('6', [
        'O God, our help in ages past,',
        'Our hope for years to come,',
        'Be thou our guard while troubles last,',
        'And our eternal home.',
      ]),
    ],
  }),

  song({
    key: 'guide-me-o-thou-great-jehovah',
    title: { en: 'Guide Me, O Thou Great Jehovah' },
    author: 'William Williams (1745); tr. Peter Williams (1771) and William Williams',
    composer: 'John Hughes',
    tune: 'CWM RHONDDA',
    meter: '8.7.8.7.8.7.7',
    year: 1745,
    tags: ['pilgrimage', 'trust', 'providence', 'closing'],
    stanzas: [
      st('1', [
        'Guide me, O thou great Jehovah,',
        'Pilgrim through this barren land;',
        'I am weak, but thou art mighty;',
        'Hold me with thy powerful hand:',
        'Bread of heaven, Bread of heaven,',
        'Feed me till I want no more;',
        'Feed me till I want no more.',
      ]),
      st('2', [
        'Open now the crystal fountain,',
        'Whence the healing stream doth flow;',
        'Let the fire and cloudy pillar',
        'Lead me all my journey through:',
        'Strong Deliverer, strong Deliverer,',
        'Be thou still my strength and shield;',
        'Be thou still my strength and shield.',
      ]),
      st('3', [
        'When I tread the verge of Jordan,',
        'Bid my anxious fears subside;',
        "Death of death, and hell's Destruction,",
        "Land me safe on Canaan's side:",
        'Songs of praises, songs of praises,',
        'I will ever give to thee;',
        'I will ever give to thee.',
      ]),
    ],
  }),

  song({
    key: 'abide-with-me',
    title: { en: 'Abide with Me', zh: '求主同住' },
    author: 'Henry F. Lyte',
    composer: 'William H. Monk',
    tune: 'EVENTIDE',
    meter: '10.10.10.10',
    year: 1847,
    tags: ['evening', 'closing', 'comfort', 'funeral'],
    stanzas: [
      st('1', [
        'Abide with me; fast falls the eventide;',
        'The darkness deepens; Lord, with me abide:',
        'When other helpers fail and comforts flee,',
        'Help of the helpless, O abide with me.',
      ]),
      st('2', [
        "Swift to its close ebbs out life's little day;",
        "Earth's joys grow dim, its glories pass away;",
        'Change and decay in all around I see:',
        'O thou who changest not, abide with me.',
      ]),
      st('3', [
        'I need thy presence every passing hour;',
        "What but thy grace can foil the tempter's power?",
        'Who, like thyself, my guide and stay can be?',
        'Through cloud and sunshine, Lord, abide with me.',
      ]),
      st('4', [
        'I fear no foe, with thee at hand to bless;',
        'Ills have no weight, and tears no bitterness:',
        "Where is death's sting? Where, grave, thy victory?",
        'I triumph still, if thou abide with me.',
      ]),
      st('5', [
        'Hold thou thy cross before my closing eyes;',
        'Shine through the gloom, and point me to the skies:',
        "Heaven's morning breaks, and earth's vain shadows flee;",
        'In life, in death, O Lord, abide with me.',
      ]),
    ],
  }),

  // ------------------------------------------------------------ easter
  song({
    key: 'christ-the-lord-is-risen-today',
    title: { en: 'Christ the Lord Is Risen Today' },
    author: 'Charles Wesley, alt.',
    composer: 'Lyra Davidica (1708)',
    tune: 'EASTER HYMN',
    meter: '7.7.7.7 with alleluias',
    year: 1739,
    tags: ['easter', 'resurrection', 'praise', 'opening'],
    stanzas: [
      st('1', [
        'Christ the Lord is risen today, Alleluia!',
        'Sons of men and angels say: Alleluia!',
        'Raise your joys and triumphs high, Alleluia!',
        'Sing, ye heavens, and earth, reply: Alleluia!',
      ]),
      st('2', [
        "Love's redeeming work is done, Alleluia!",
        'Fought the fight, the battle won: Alleluia!',
        'Death in vain forbids him rise, Alleluia!',
        'Christ has opened paradise. Alleluia!',
      ]),
      st('3', [
        'Lives again our glorious King, Alleluia!',
        'Where, O death, is now thy sting? Alleluia!',
        'Once he died our souls to save, Alleluia!',
        'Where thy victory, O grave? Alleluia!',
      ]),
      st('4', [
        'Soar we now where Christ has led, Alleluia!',
        'Following our exalted Head: Alleluia!',
        'Made like him, like him we rise, Alleluia!',
        'Ours the cross, the grave, the skies. Alleluia!',
      ]),
    ],
  }),

  song({
    key: 'thine-be-the-glory',
    title: { en: 'Thine Be the Glory' },
    author: 'Edmond L. Budry (1884); tr. Richard B. Hoyle (1923)',
    composer: 'George Frideric Handel',
    tune: 'JUDAS MACCABEUS',
    meter: '10.11.11.11 with refrain',
    year: 1884,
    refrain_after_each: true,
    tags: ['easter', 'resurrection', 'praise', 'closing'],
    stanzas: [
      st('1', [
        'Thine be the glory, risen, conquering Son;',
        "Endless is the victory thou o'er death hast won;",
        'Angels in bright raiment rolled the stone away,',
        'Kept the folded grave-clothes where thy body lay.',
      ]),
      st('R', [
        'Thine be the glory, risen, conquering Son;',
        "Endless is the victory thou o'er death hast won.",
      ]),
      st('2', [
        'Lo! Jesus meets us, risen from the tomb;',
        'Lovingly he greets us, scatters fear and gloom;',
        'Let the Church with gladness hymns of triumph sing,',
        'For her Lord now liveth; death hath lost its sting.',
      ]),
      st('3', [
        'No more we doubt thee, glorious Prince of life;',
        'Life is naught without thee: aid us in our strife;',
        'Make us more than conquerors, through thy deathless love;',
        'Bring us safe through Jordan to thy home above.',
      ]),
    ],
  }),

  // ------------------------------------------------------------ advent & christmas
  song({
    key: 'o-come-o-come-emmanuel',
    title: { en: 'O Come, O Come, Emmanuel' },
    author: 'Latin (12th cent.); tr. John Mason Neale (1851), alt.',
    composer: 'French processional (15th cent.)',
    tune: 'VENI EMMANUEL',
    meter: '8.8.8.8 with refrain',
    year: 1851,
    refrain_after_each: true,
    tags: ['advent', 'christmas'],
    stanzas: [
      st('1', [
        'O come, O come, Emmanuel,',
        'And ransom captive Israel,',
        'That mourns in lonely exile here',
        'Until the Son of God appear.',
      ]),
      st('R', ['Rejoice! Rejoice! Emmanuel', 'Shall come to thee, O Israel.']),
      st('2', [
        'O come, thou Rod of Jesse, free',
        "Thine own from Satan's tyranny;",
        'From depths of hell thy people save,',
        "And give them victory o'er the grave.",
      ]),
      st('3', [
        'O come, thou Dayspring, come and cheer',
        'Our spirits by thine advent here;',
        'Disperse the gloomy clouds of night,',
        "And death's dark shadows put to flight.",
      ]),
      st('4', [
        'O come, thou Key of David, come,',
        'And open wide our heavenly home;',
        'Make safe the way that leads on high,',
        'And close the path to misery.',
      ]),
      st('5', [
        'O come, O come, thou Lord of might,',
        "Who to thy tribes, on Sinai's height,",
        'In ancient times didst give the law',
        'In cloud, and majesty, and awe.',
      ]),
    ],
  }),

  song({
    key: 'once-in-royal-davids-city',
    title: { en: "Once in Royal David's City" },
    author: 'Cecil Frances Alexander',
    composer: 'Henry J. Gauntlett',
    tune: 'IRBY',
    meter: '8.7.8.7.7.7',
    year: 1848,
    tags: ['christmas', 'lessons-and-carols', 'opening'],
    stanzas: [
      st('1', [
        "Once in royal David's city",
        'Stood a lowly cattle shed,',
        'Where a mother laid her baby',
        'In a manger for his bed:',
        'Mary was that mother mild,',
        'Jesus Christ her little child.',
      ]),
      st('2', [
        'He came down to earth from heaven,',
        'Who is God and Lord of all,',
        'And his shelter was a stable,',
        'And his cradle was a stall;',
        'With the poor, and mean, and lowly,',
        'Lived on earth our Saviour holy.',
      ]),
      st('3', [
        'And through all his wondrous childhood',
        'He would honour and obey,',
        'Love and watch the lowly maiden,',
        'In whose gentle arms he lay:',
        'Christian children all must be',
        'Mild, obedient, good as he.',
      ]),
      st('4', [
        "For he is our childhood's pattern;",
        'Day by day, like us, he grew;',
        'He was little, weak, and helpless,',
        'Tears and smiles like us he knew;',
        'And he feeleth for our sadness,',
        'And he shareth in our gladness.',
      ]),
      st('5', [
        'And our eyes at last shall see him,',
        'Through his own redeeming love;',
        'For that child so dear and gentle',
        'Is our Lord in heaven above;',
        'And he leads his children on',
        'To the place where he is gone.',
      ]),
      st('6', [
        'Not in that poor lowly stable,',
        'With the oxen standing by,',
        'We shall see him; but in heaven,',
        "Set at God's right hand on high;",
        'When like stars his children crowned',
        'All in white shall wait around.',
      ]),
    ],
  }),

  song({
    key: 'o-little-town-of-bethlehem',
    title: { en: 'O Little Town of Bethlehem', zh: '伯利恒小城' },
    author: 'Phillips Brooks',
    composer: 'Lewis H. Redner',
    tune: 'ST. LOUIS',
    meter: '8.6.8.6.7.6.8.6',
    year: 1868,
    tags: ['christmas', 'lessons-and-carols'],
    stanzas: [
      st('1', [
        'O little town of Bethlehem,',
        'How still we see thee lie!',
        'Above thy deep and dreamless sleep',
        'The silent stars go by;',
        'Yet in thy dark streets shineth',
        'The everlasting Light;',
        'The hopes and fears of all the years',
        'Are met in thee tonight.',
      ]),
      st('2', [
        'For Christ is born of Mary,',
        'And gathered all above,',
        'While mortals sleep, the angels keep',
        'Their watch of wondering love.',
        'O morning stars, together',
        'Proclaim the holy birth!',
        'And praises sing to God the King,',
        'And peace to men on earth.',
      ]),
      st('3', [
        'How silently, how silently,',
        'The wondrous gift is given!',
        'So God imparts to human hearts',
        'The blessings of his heaven.',
        'No ear may hear his coming,',
        'But in this world of sin,',
        'Where meek souls will receive him still,',
        'The dear Christ enters in.',
      ]),
      st('4', [
        'O holy Child of Bethlehem,',
        'Descend to us, we pray;',
        'Cast out our sin, and enter in,',
        'Be born in us today.',
        'We hear the Christmas angels',
        'The great glad tidings tell;',
        'O come to us, abide with us,',
        'Our Lord Emmanuel!',
      ]),
    ],
  }),

  song({
    key: 'o-come-all-ye-faithful',
    title: { en: 'O Come, All Ye Faithful' },
    author: 'attr. John F. Wade (c. 1743); tr. Frederick Oakeley (1841) and others',
    composer: 'attr. John F. Wade',
    tune: 'ADESTE FIDELES',
    meter: 'Irregular with refrain',
    year: 1743,
    refrain_after_each: true,
    tags: ['christmas', 'lessons-and-carols', 'opening'],
    stanzas: [
      st('1', [
        'O come, all ye faithful, joyful and triumphant,',
        'O come ye, O come ye to Bethlehem;',
        'Come and behold him, born the King of angels:',
      ]),
      st('R', [
        'O come, let us adore him,',
        'O come, let us adore him,',
        'O come, let us adore him, Christ the Lord.',
      ]),
      st('2', [
        'God of God, Light of Light,',
        'Lo, he abhors not the Virgin’s womb;',
        'Very God, begotten, not created:',
      ]),
      st('3', [
        'Sing, choirs of angels, sing in exultation,',
        'Sing, all ye citizens of heaven above!',
        'Glory to God in the highest:',
      ]),
      st('4', [
        'Yea, Lord, we greet thee, born this happy morning;',
        'Jesus, to thee be glory given;',
        'Word of the Father, now in flesh appearing:',
      ]),
    ],
  }),

  song({
    key: 'hark-the-herald',
    title: { en: 'Hark! the Herald Angels Sing', zh: '听啊，天使高声唱' },
    author: 'Charles Wesley (1739), alt. George Whitefield (1753) and others',
    composer: 'Felix Mendelssohn; arr. William H. Cummings',
    tune: 'MENDELSSOHN',
    meter: '7.7.7.7 D with refrain',
    year: 1739,
    refrain_after_each: true,
    tags: ['christmas', 'lessons-and-carols', 'incarnation'],
    stanzas: [
      st('1', [
        'Hark! the herald angels sing,',
        '“Glory to the newborn King;',
        'Peace on earth, and mercy mild,',
        'God and sinners reconciled!”',
        'Joyful, all ye nations, rise,',
        'Join the triumph of the skies;',
        'With th’ angelic host proclaim,',
        '“Christ is born in Bethlehem!”',
      ]),
      st('R', ['Hark! the herald angels sing,', '“Glory to the newborn King!”']),
      st('2', [
        'Christ, by highest heaven adored;',
        'Christ, the everlasting Lord;',
        'Late in time behold him come,',
        'Offspring of the Virgin’s womb:',
        'Veiled in flesh the Godhead see;',
        'Hail th’ incarnate Deity,',
        'Pleased as man with men to dwell,',
        'Jesus, our Emmanuel.',
      ]),
      st('3', [
        'Hail the heaven-born Prince of Peace!',
        'Hail the Sun of Righteousness!',
        'Light and life to all he brings,',
        'Risen with healing in his wings.',
        'Mild he lays his glory by,',
        'Born that man no more may die,',
        'Born to raise the sons of earth,',
        'Born to give them second birth.',
      ]),
    ],
  }),

  song({
    key: 'silent-night',
    title: { en: 'Silent Night', zh: '平安夜' },
    author: 'Joseph Mohr (1818); tr. John F. Young (1859)',
    composer: 'Franz X. Gruber',
    tune: 'STILLE NACHT',
    meter: 'Irregular',
    year: 1818,
    tags: ['christmas', 'lessons-and-carols', 'christmas-eve'],
    stanzas: [
      st('1', [
        'Silent night, holy night,',
        'All is calm, all is bright',
        'Round yon virgin mother and child.',
        'Holy infant, so tender and mild,',
        'Sleep in heavenly peace,',
        'Sleep in heavenly peace.',
      ]),
      st('2', [
        'Silent night, holy night,',
        'Shepherds quake at the sight;',
        'Glories stream from heaven afar,',
        'Heavenly hosts sing Alleluia!',
        'Christ the Saviour is born,',
        'Christ the Saviour is born!',
      ]),
      st('3', [
        'Silent night, holy night,',
        "Son of God, love's pure light",
        'Radiant beams from thy holy face,',
        'With the dawn of redeeming grace,',
        'Jesus, Lord, at thy birth,',
        'Jesus, Lord, at thy birth.',
      ]),
    ],
  }),

  song({
    key: 'joy-to-the-world',
    title: { en: 'Joy to the World', zh: '普世欢腾' },
    author: 'Isaac Watts',
    composer: 'arr. Lowell Mason',
    tune: 'ANTIOCH',
    meter: '8.6.8.6 with repeats',
    year: 1719,
    psalm: 98,
    tags: ['christmas', 'lessons-and-carols', 'kingship', 'psalm-98', 'closing'],
    stanzas: [
      st('1', [
        'Joy to the world! the Lord is come;',
        'Let earth receive her King;',
        'Let every heart prepare him room,',
        'And heaven and nature sing.',
      ]),
      st('2', [
        'Joy to the earth! the Saviour reigns;',
        'Let men their songs employ;',
        'While fields and floods, rocks, hills, and plains',
        'Repeat the sounding joy.',
      ]),
      st('3', [
        'No more let sins and sorrows grow,',
        'Nor thorns infest the ground;',
        'He comes to make his blessings flow',
        'Far as the curse is found.',
      ]),
      st('4', [
        'He rules the world with truth and grace,',
        'And makes the nations prove',
        'The glories of his righteousness,',
        'And wonders of his love.',
      ]),
    ],
  }),

  // ------------------------------------------------------------ metrical psalms (Scottish Psalter 1650)
  song({
    key: 'psalm-23-scottish',
    title: { en: "Psalm 23: The Lord's My Shepherd" },
    author: 'Scottish Psalter (1650)',
    composer: 'Jessie S. Irvine',
    tune: 'CRIMOND',
    meter: '8.6.8.6',
    year: 1650,
    category: 'psalm',
    psalm: 23,
    tags: ['psalm', 'trust', 'comfort', 'lords-supper', 'funeral'],
    stanzas: [
      st('1', [
        "The Lord's my shepherd, I'll not want;",
        'He makes me down to lie',
        'In pastures green: he leadeth me',
        'The quiet waters by.',
      ]),
      st('2', [
        'My soul he doth restore again;',
        'And me to walk doth make',
        'Within the paths of righteousness,',
        "Ev'n for his own name's sake.",
      ]),
      st('3', [
        "Yea, though I walk in death's dark vale,",
        'Yet will I fear none ill;',
        'For thou art with me; and thy rod',
        'And staff me comfort still.',
      ]),
      st('4', [
        'My table thou hast furnishèd',
        'In presence of my foes;',
        'My head thou dost with oil anoint,',
        'And my cup overflows.',
      ]),
      st('5', [
        'Goodness and mercy all my life',
        'Shall surely follow me;',
        "And in God's house for evermore",
        'My dwelling-place shall be.',
      ]),
    ],
  }),

  song({
    key: 'psalm-100-old-hundredth',
    title: { en: 'Psalm 100: All People That on Earth Do Dwell' },
    author: 'William Kethe (1561); Scottish Psalter (1650)',
    composer: 'Louis Bourgeois (Genevan Psalter, 1551)',
    tune: 'OLD HUNDREDTH',
    meter: '8.8.8.8',
    year: 1561,
    category: 'psalm',
    psalm: 100,
    tags: ['psalm', 'praise', 'opening', 'call-to-worship'],
    stanzas: [
      st('1', [
        'All people that on earth do dwell,',
        'Sing to the Lord with cheerful voice.',
        'Him serve with mirth, his praise forth tell;',
        'Come ye before him and rejoice.',
      ]),
      st('2', [
        'Know that the Lord is God indeed;',
        'Without our aid he did us make:',
        'We are his flock, he doth us feed,',
        'And for his sheep he doth us take.',
      ]),
      st('3', [
        'O enter then his gates with praise;',
        'Approach with joy his courts unto:',
        'Praise, laud, and bless his name always,',
        'For it is seemly so to do.',
      ]),
      st('4', [
        'For why? the Lord our God is good;',
        'His mercy is for ever sure;',
        'His truth at all times firmly stood,',
        'And shall from age to age endure.',
      ]),
    ],
  }),

  // ------------------------------------------------------------ service music
  song({
    key: 'doxology',
    title: { en: 'Doxology', zh: '三一颂' },
    author: 'Thomas Ken',
    composer: 'Louis Bourgeois (Genevan Psalter, 1551)',
    tune: 'OLD HUNDREDTH',
    meter: '8.8.8.8',
    year: 1674,
    category: 'doxology',
    tags: ['doxology', 'offering', 'trinity', 'praise'],
    stanzas: [
      st(
        '1',
        [
          'Praise God, from whom all blessings flow;',
          'Praise him, all creatures here below;',
          'Praise him above, ye heavenly host;',
          'Praise Father, Son, and Holy Ghost. Amen.',
        ],
        ['赞美真神万福之根，', '世上万民都当颂扬，', '天上万军也当赞美，', '赞美圣父、圣子、圣灵。阿们。'],
      ),
    ],
  }),

  song({
    key: 'gloria-patri',
    title: { en: 'Gloria Patri', zh: '荣耀颂' },
    author: 'Traditional (early Church)',
    composer: 'Henry W. Greatorex',
    tune: 'GREATOREX',
    meter: 'Irregular',
    year: null,
    category: 'response',
    tags: ['response', 'trinity', 'praise', 'closing'],
    stanzas: [
      st(
        '1',
        [
          'Glory be to the Father,',
          'and to the Son, and to the Holy Ghost;',
          'as it was in the beginning, is now, and ever shall be,',
          'world without end. Amen, Amen.',
        ],
        ['荣耀归于圣父、圣子和圣灵；', '起初这样，现在这样，', '以后也这样，永无穷尽。', '阿们，阿们。'],
      ),
    ],
  }),
];
