// Seed liturgical texts: creeds, prayers, Scripture sentences and sacramental forms.
//
// Format (see LiturgyText in shared/types.ts): "L: " leader, "C: " congregation, "A: " all;
// unprefixed lines are plain; a blank line is a paragraph / slide break. zh bodies use the same prefixes.
//
// Scripture: English is the King James Version (1769 text; "LORD" restored where the Hebrew is YHWH);
// Chinese is the 和合本 (Chinese Union Version, 1919) in Simplified characters, verbatim except that
// translator's notes and outer quotation marks have been removed.
// "Canon original" texts were written for this app and may be freely used and adapted.

import type { L10n, LiturgyText, TextCategory } from '../../shared/types.ts';

export type SeedText = Omit<LiturgyText, 'id' | 'parts'> & { key: string; parts?: LiturgyText['parts'] };

const KJV_CUV = 'KJV / 和合本 (CUV 1919)';

function text(
  key: string,
  category: TextCategory,
  title: L10n,
  en: string[],
  zh: string[] | null,
  source: string,
  tags: string[],
): SeedText {
  const body: L10n = { en: en.join('\n') };
  if (zh) body.zh = zh.join('\n');
  return { key, category, title, body, source, tags, public_domain: true };
}

export const SEED_TEXTS: SeedText[] = [
  // ------------------------------------------------------------ calls to worship
  text(
    'call-psalm-95',
    'call_to_worship',
    { en: 'Call to Worship: Psalm 95', zh: '宣召：诗篇95篇' },
    [
      'L: O come, let us sing unto the LORD:',
      'C: let us make a joyful noise to the rock of our salvation.',
      'L: Let us come before his presence with thanksgiving,',
      'C: and make a joyful noise unto him with psalms.',
      '',
      'L: For the LORD is a great God,',
      'C: and a great King above all gods.',
      'L: In his hand are the deep places of the earth:',
      'C: the strength of the hills is his also.',
      '',
      'L: The sea is his, and he made it:',
      'C: and his hands formed the dry land.',
      'L: O come, let us worship and bow down:',
      'C: let us kneel before the LORD our maker.',
      '',
      'L: For he is our God;',
      'C: and we are the people of his pasture, and the sheep of his hand.',
    ],
    [
      'L: 来啊，我们要向耶和华歌唱，',
      'C: 向拯救我们的磐石欢呼！',
      'L: 我们要来感谢他，',
      'C: 用诗歌向他欢呼！',
      '',
      'L: 因耶和华为大神，为大王，',
      'C: 超乎万神之上。',
      'L: 地的深处在他手中；',
      'C: 山的高峰也属他。',
      '',
      'L: 海洋属他，是他造的；',
      'C: 旱地也是他手造成的。',
      'L: 来啊，我们要屈身敬拜，',
      'C: 在造我们的耶和华面前跪下。',
      '',
      'L: 因为他是我们的神；',
      'C: 我们是他草场的羊，是他手下的民。',
    ],
    `Psalm 95:1-7a — ${KJV_CUV}`,
    ['call-to-worship', 'psalm', 'responsive', 'praise'],
  ),

  text(
    'call-psalm-100',
    'call_to_worship',
    { en: 'Call to Worship: Psalm 100', zh: '宣召：诗篇100篇' },
    [
      'L: Make a joyful noise unto the LORD, all ye lands.',
      'C: Serve the LORD with gladness: come before his presence with singing.',
      '',
      'L: Know ye that the LORD he is God:',
      'C: it is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture.',
      '',
      'L: Enter into his gates with thanksgiving, and into his courts with praise:',
      'C: be thankful unto him, and bless his name.',
      '',
      'A: For the LORD is good; his mercy is everlasting; and his truth endureth to all generations.',
    ],
    [
      'L: 普天下当向耶和华欢呼！',
      'C: 你们当乐意事奉耶和华，当来向他歌唱！',
      '',
      'L: 你们当晓得耶和华是神！',
      'C: 我们是他造的，也是属他的；我们是他的民，也是他草场的羊。',
      '',
      'L: 当称谢进入他的门；当赞美进入他的院。',
      'C: 当感谢他，称颂他的名！',
      '',
      'A: 因为耶和华本为善。他的慈爱存到永远；他的信实直到万代。',
    ],
    `Psalm 100 — ${KJV_CUV}`,
    ['call-to-worship', 'psalm', 'responsive', 'praise', 'thanksgiving'],
  ),

  text(
    'call-psalm-24',
    'call_to_worship',
    { en: 'Call to Worship: Psalm 24', zh: '宣召：诗篇24篇' },
    [
      'L: Lift up your heads, O ye gates; and be ye lift up, ye everlasting doors; and the King of glory shall come in.',
      'C: Who is this King of glory?',
      'L: The LORD strong and mighty, the LORD mighty in battle.',
      '',
      'L: Lift up your heads, O ye gates; even lift them up, ye everlasting doors; and the King of glory shall come in.',
      'C: Who is this King of glory?',
      'A: The LORD of hosts, he is the King of glory.',
    ],
    [
      'L: 众城门哪，你们要抬起头来！永久的门户，你们要被举起！那荣耀的王将要进来！',
      'C: 荣耀的王是谁呢？',
      'L: 就是有力有能的耶和华，在战场上有能的耶和华！',
      '',
      'L: 众城门哪，你们要抬起头来！永久的门户，你们要把头抬起！那荣耀的王将要进来！',
      'C: 荣耀的王是谁呢？',
      'A: 万军之耶和华，他是荣耀的王！',
    ],
    `Psalm 24:7-10 — ${KJV_CUV}`,
    ['call-to-worship', 'psalm', 'responsive', 'kingship', 'advent', 'ascension'],
  ),

  text(
    'call-isaiah-6',
    'call_to_worship',
    { en: 'Call to Worship: Isaiah 6:3', zh: '宣召：以赛亚书6:3' },
    ['L: Holy, holy, holy, is the LORD of hosts:', 'C: the whole earth is full of his glory.'],
    ['L: 圣哉！圣哉！圣哉！万军之耶和华；', 'C: 他的荣光充满全地！'],
    `Isaiah 6:3 — ${KJV_CUV}`,
    ['call-to-worship', 'holiness', 'trinity', 'responsive'],
  ),

  // ------------------------------------------------------------ invocation
  text(
    'votum-salutation',
    'invocation',
    { en: 'Votum and Salutation', zh: '宣召与问安' },
    [
      'L: Our help is in the name of the LORD, who made heaven and earth.',
      '',
      'L: Grace to you and peace from God our Father, and the Lord Jesus Christ.',
      'C: Amen.',
    ],
    [
      'L: 我们得帮助，是在乎倚靠造天地之耶和华的名。',
      '',
      'L: 愿恩惠、平安从我们的父神并主耶稣基督归与你们！',
      'C: 阿们。',
    ],
    `Psalm 124:8; Romans 1:7 — ${KJV_CUV}`,
    ['invocation', 'votum', 'opening'],
  ),

  text(
    'invocation-prayer',
    'invocation',
    { en: 'Prayer of Invocation', zh: '祈祷（求主同在）' },
    [
      'L: Almighty and everlasting God, our heavenly Father:',
      "L: you have called us out of darkness into your marvellous light, and gathered us as your people on this Lord's Day.",
      'L: Open our lips, that our mouths may declare your praise.',
      'L: By your Holy Spirit lift our hearts to you, that we may worship you in spirit and in truth, and give you the glory due to your name;',
      'L: through Jesus Christ our Lord, who lives and reigns with you and the Holy Spirit, one God, for ever and ever.',
      'A: Amen.',
    ],
    [
      'L: 全能永在的神，我们在天上的父：',
      'L: 你召我们出黑暗、入奇妙的光明，又在这主日招聚我们成为你的子民。',
      'L: 求你使我们嘴唇张开，我们的口便传扬赞美你的话。',
      'L: 求你借着圣灵提升我们的心归向你，使我们用心灵和诚实敬拜你，将你名所当得的荣耀归给你；',
      'L: 奉我们主耶稣基督的名，他与你和圣灵同为独一的神，永活永治，直到永远。',
      'A: 阿们。',
    ],
    'Canon original',
    ['invocation', 'prayer', 'opening'],
  ),

  // ------------------------------------------------------------ law
  text(
    'ten-commandments',
    'liturgy',
    { en: 'The Ten Commandments', zh: '十诫' },
    [
      'L: God spake all these words, saying,',
      'L: I am the LORD thy God, which have brought thee out of the land of Egypt, out of the house of bondage.',
      '',
      'L: Thou shalt have no other gods before me.',
      '',
      'L: Thou shalt not make unto thee any graven image, or any likeness of any thing that is in heaven above, or that is in the earth beneath, or that is in the water under the earth:',
      'L: Thou shalt not bow down thyself to them, nor serve them: for I the LORD thy God am a jealous God, visiting the iniquity of the fathers upon the children unto the third and fourth generation of them that hate me;',
      'L: And shewing mercy unto thousands of them that love me, and keep my commandments.',
      '',
      'L: Thou shalt not take the name of the LORD thy God in vain; for the LORD will not hold him guiltless that taketh his name in vain.',
      '',
      'L: Remember the sabbath day, to keep it holy.',
      'L: Six days shalt thou labour, and do all thy work:',
      'L: But the seventh day is the sabbath of the LORD thy God: in it thou shalt not do any work, thou, nor thy son, nor thy daughter, thy manservant, nor thy maidservant, nor thy cattle, nor thy stranger that is within thy gates:',
      'L: For in six days the LORD made heaven and earth, the sea, and all that in them is, and rested the seventh day: wherefore the LORD blessed the sabbath day, and hallowed it.',
      '',
      'L: Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee.',
      '',
      'L: Thou shalt not kill.',
      'L: Thou shalt not commit adultery.',
      'L: Thou shalt not steal.',
      'L: Thou shalt not bear false witness against thy neighbour.',
      '',
      "L: Thou shalt not covet thy neighbour's house, thou shalt not covet thy neighbour's wife, nor his manservant, nor his maidservant, nor his ox, nor his ass, nor any thing that is thy neighbour's.",
    ],
    [
      'L: 神吩咐这一切的话说：',
      'L: 我是耶和华—你的神，曾将你从埃及地为奴之家领出来。',
      '',
      'L: 除了我以外，你不可有别的神。',
      '',
      'L: 不可为自己雕刻偶像，也不可做甚么形像仿佛上天、下地，和地底下、水中的百物。',
      'L: 不可跪拜那些像，也不可事奉它，因为我耶和华—你的神是忌邪的神。恨我的，我必追讨他的罪，自父及子，直到三四代；',
      'L: 爱我、守我诫命的，我必向他们发慈爱，直到千代。',
      '',
      'L: 不可妄称耶和华—你神的名；因为妄称耶和华名的，耶和华必不以他为无罪。',
      '',
      'L: 当记念安息日，守为圣日。',
      'L: 六日要劳碌做你一切的工，',
      'L: 但第七日是向耶和华—你神当守的安息日。这一日你和你的儿女、仆婢、牲畜，并你城里寄居的客旅，无论何工都不可做；',
      'L: 因为六日之内，耶和华造天、地、海，和其中的万物，第七日便安息，所以耶和华赐福与安息日，定为圣日。',
      '',
      'L: 当孝敬父母，使你的日子在耶和华—你神所赐你的地上得以长久。',
      '',
      'L: 不可杀人。',
      'L: 不可奸淫。',
      'L: 不可偷盗。',
      'L: 不可作假见证陷害人。',
      '',
      'L: 不可贪恋人的房屋；也不可贪恋人的妻子、仆婢、牛驴，并他一切所有的。',
    ],
    `Exodus 20:1-17 — ${KJV_CUV}`,
    ['law', 'ten-commandments', 'confession'],
  ),

  text(
    'summary-of-the-law',
    'liturgy',
    { en: 'The Summary of the Law', zh: '律法的总纲' },
    [
      'L: Hear what our Lord Jesus Christ saith:',
      'L: Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind.',
      'L: This is the first and great commandment.',
      'L: And the second is like unto it, Thou shalt love thy neighbour as thyself.',
      'L: On these two commandments hang all the law and the prophets.',
    ],
    [
      'L: 请听主耶稣基督的话：',
      'L: 你要尽心、尽性、尽意爱主—你的神。',
      'L: 这是诫命中的第一，且是最大的。',
      'L: 其次也相仿，就是要爱人如己。',
      'L: 这两条诫命是律法和先知一切道理的总纲。',
    ],
    `Matthew 22:37-40 — ${KJV_CUV}`,
    ['law', 'summary-of-the-law', 'confession'],
  ),

  // ------------------------------------------------------------ confession
  text(
    'general-confession',
    'confession',
    { en: 'General Confession', zh: '公认罪文' },
    [
      'L: Let us humbly confess our sins unto Almighty God.',
      '',
      'A: Almighty and most merciful Father;',
      'A: we have erred, and strayed from thy ways like lost sheep.',
      'A: We have followed too much the devices and desires of our own hearts.',
      'A: We have offended against thy holy laws.',
      'A: We have left undone those things which we ought to have done;',
      'A: and we have done those things which we ought not to have done;',
      'A: and there is no health in us.',
      '',
      'A: But thou, O Lord, have mercy upon us, miserable offenders.',
      'A: Spare thou them, O God, which confess their faults.',
      'A: Restore thou them that are penitent;',
      'A: according to thy promises declared unto mankind in Christ Jesu our Lord.',
      'A: And grant, O most merciful Father, for his sake;',
      'A: that we may hereafter live a godly, righteous, and sober life,',
      'A: to the glory of thy holy Name. Amen.',
    ],
    [
      'L: 我们当存谦卑的心，向全能的神承认我们的罪。',
      '',
      'A: 全能、至慈的天父：',
      'A: 我们走迷了路，偏离你的道，如同迷失的羊。',
      'A: 我们太过随从自己心中的计谋和私欲。',
      'A: 我们违犯了你圣洁的律法。',
      'A: 当做的，我们没有去做；',
      'A: 不当做的，我们却做了；',
      'A: 我们里面毫无完全之处。',
      '',
      'A: 主啊，求你怜悯我们这些可怜的罪人。',
      'A: 神啊，求你宽恕承认己过的人；',
      'A: 使悔改的人得以复兴；',
      'A: 照着你在我们的主基督耶稣里向世人所应许的。',
      'A: 至慈的天父啊，求你因祂的缘故施恩，',
      'A: 使我们从今以后过敬虔、公义、自守的生活，',
      'A: 好叫荣耀归于你的圣名。阿们。',
    ],
    'Book of Common Prayer (1662), Morning Prayer; Chinese tr. Canon (2026)',
    ['confession', 'prayer', 'unison'],
  ),

  text(
    'confession-psalm-51',
    'confession',
    { en: 'Prayer of Confession: Psalm 51', zh: '认罪祷告：诗篇51篇' },
    [
      'A: Have mercy upon me, O God, according to thy lovingkindness:',
      'A: according unto the multitude of thy tender mercies blot out my transgressions.',
      'A: Wash me throughly from mine iniquity, and cleanse me from my sin.',
      'A: For I acknowledge my transgressions: and my sin is ever before me.',
      'A: Against thee, thee only, have I sinned, and done this evil in thy sight: that thou mightest be justified when thou speakest, and be clear when thou judgest.',
      '',
      'A: Purge me with hyssop, and I shall be clean: wash me, and I shall be whiter than snow.',
      'A: Hide thy face from my sins, and blot out all mine iniquities.',
      'A: Create in me a clean heart, O God; and renew a right spirit within me.',
      'A: Cast me not away from thy presence; and take not thy holy spirit from me.',
      'A: Restore unto me the joy of thy salvation; and uphold me with thy free spirit.',
    ],
    [
      'A: 神啊，求你按你的慈爱怜恤我！',
      'A: 按你丰盛的慈悲涂抹我的过犯！',
      'A: 求你将我的罪孽洗除净尽，并洁除我的罪！',
      'A: 因为，我知道我的过犯；我的罪常在我面前。',
      'A: 我向你犯罪，惟独得罪了你；在你眼前行了这恶，以致你责备我的时候显为公义，判断我的时候显为清正。',
      '',
      'A: 求你用牛膝草洁净我，我就干净；求你洗涤我，我就比雪更白。',
      'A: 求你掩面不看我的罪，涂抹我一切的罪孽。',
      'A: 神啊，求你为我造清洁的心，使我里面重新有正直的灵。',
      'A: 不要丢弃我，使我离开你的面；不要从我收回你的圣灵。',
      'A: 求你使我仍得救恩之乐，赐我乐意的灵扶持我。',
    ],
    `Psalm 51:1-4, 7, 9-12 — ${KJV_CUV}`,
    ['confession', 'psalm', 'unison'],
  ),

  // ------------------------------------------------------------ assurance of pardon
  text(
    'assurance-1-john-1',
    'assurance',
    { en: 'Assurance of Pardon: 1 John 1:8-9', zh: '赦罪的确据：约翰一书1:8-9' },
    [
      'L: If we say that we have no sin, we deceive ourselves, and the truth is not in us.',
      'L: If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.',
      'C: Thanks be to God.',
    ],
    [
      'L: 我们若说自己无罪，便是自欺，真理不在我们心里了。',
      'L: 我们若认自己的罪，神是信实的，是公义的，必要赦免我们的罪，洗净我们一切的不义。',
      'C: 感谢神！',
    ],
    `1 John 1:8-9 — ${KJV_CUV}`,
    ['assurance', 'forgiveness'],
  ),

  text(
    'assurance-isaiah-1',
    'assurance',
    { en: 'Assurance of Pardon: Isaiah 1:18', zh: '赦罪的确据：以赛亚书1:18' },
    [
      'L: Come now, and let us reason together, saith the LORD:',
      'L: though your sins be as scarlet, they shall be as white as snow;',
      'L: though they be red like crimson, they shall be as wool.',
      'C: Thanks be to God.',
    ],
    [
      'L: 耶和华说：你们来，我们彼此辩论。',
      'L: 你们的罪虽像朱红，必变成雪白；',
      'L: 虽红如丹颜，必白如羊毛。',
      'C: 感谢神！',
    ],
    `Isaiah 1:18 — ${KJV_CUV}`,
    ['assurance', 'forgiveness'],
  ),

  text(
    'assurance-psalm-103',
    'assurance',
    { en: 'Assurance of Pardon: Psalm 103:8-12', zh: '赦罪的确据：诗篇103:8-12' },
    [
      'L: The LORD is merciful and gracious, slow to anger, and plenteous in mercy.',
      'L: He will not always chide: neither will he keep his anger for ever.',
      'L: He hath not dealt with us after our sins; nor rewarded us according to our iniquities.',
      'L: For as the heaven is high above the earth, so great is his mercy toward them that fear him.',
      'L: As far as the east is from the west, so far hath he removed our transgressions from us.',
      'C: Thanks be to God.',
    ],
    [
      'L: 耶和华有怜悯，有恩典，不轻易发怒，且有丰盛的慈爱。',
      'L: 他不长久责备，也不永远怀怒。',
      'L: 他没有按我们的罪过待我们，也没有照我们的罪孽报应我们。',
      'L: 天离地何等的高，他的慈爱向敬畏他的人也是何等的大！',
      'L: 东离西有多远，他叫我们的过犯离我们也有多远！',
      'C: 感谢神！',
    ],
    `Psalm 103:8-12 — ${KJV_CUV}`,
    ['assurance', 'forgiveness', 'psalm'],
  ),

  // ------------------------------------------------------------ creeds & catechism
  text(
    'apostles-creed',
    'creed',
    { en: "The Apostles' Creed", zh: '使徒信经' },
    [
      'A: I believe in God the Father Almighty, Maker of heaven and earth:',
      '',
      'A: And in Jesus Christ his only Son our Lord;',
      'A: who was conceived by the Holy Ghost, born of the Virgin Mary;',
      'A: suffered under Pontius Pilate, was crucified, dead, and buried;',
      'A: he descended into hell;',
      'A: the third day he rose again from the dead;',
      'A: he ascended into heaven, and sitteth on the right hand of God the Father Almighty;',
      'A: from thence he shall come to judge the quick and the dead.',
      '',
      'A: I believe in the Holy Ghost;',
      'A: the holy catholic Church; the communion of saints;',
      'A: the forgiveness of sins; the resurrection of the body;',
      'A: and the life everlasting. Amen.',
    ],
    [
      'A: 我信上帝，全能的父，创造天地的主。',
      '',
      'A: 我信我主耶稣基督，上帝的独生子；',
      'A: 因着圣灵感孕，从童贞女马利亚所生；',
      'A: 在本丢彼拉多手下受难，被钉于十字架，受死，埋葬；',
      'A: 降在阴间；',
      'A: 第三天从死人中复活；',
      'A: 升天，坐在全能父上帝的右边；',
      'A: 将来必从那里降临，审判活人死人。',
      '',
      'A: 我信圣灵；',
      'A: 我信圣而公之教会；我信圣徒相通；',
      'A: 我信罪得赦免；我信身体复活；',
      'A: 我信永生。阿们。',
    ],
    'Traditional English text (Book of Common Prayer, 1662); Chinese Protestant common text',
    ['creed', 'confession-of-faith', 'unison'],
  ),

  text(
    'nicene-creed',
    'creed',
    { en: 'The Nicene Creed', zh: '尼西亚信经' },
    [
      'A: I believe in one God the Father Almighty,',
      'A: Maker of heaven and earth, and of all things visible and invisible:',
      '',
      'A: And in one Lord Jesus Christ, the only-begotten Son of God,',
      'A: begotten of his Father before all worlds,',
      'A: God of God, Light of Light, very God of very God,',
      'A: begotten, not made, being of one substance with the Father;',
      'A: by whom all things were made:',
      'A: who for us men and for our salvation came down from heaven,',
      'A: and was incarnate by the Holy Ghost of the Virgin Mary, and was made man,',
      'A: and was crucified also for us under Pontius Pilate.',
      'A: He suffered and was buried,',
      'A: and the third day he rose again according to the Scriptures,',
      'A: and ascended into heaven, and sitteth on the right hand of the Father.',
      'A: And he shall come again with glory to judge both the quick and the dead:',
      'A: whose kingdom shall have no end.',
      '',
      'A: And I believe in the Holy Ghost, the Lord and giver of life,',
      'A: who proceedeth from the Father and the Son;',
      'A: who with the Father and the Son together is worshipped and glorified;',
      'A: who spake by the Prophets.',
      'A: And I believe one holy catholic and apostolic Church.',
      'A: I acknowledge one Baptism for the remission of sins.',
      'A: And I look for the resurrection of the dead,',
      'A: and the life of the world to come. Amen.',
    ],
    null,
    'Book of Common Prayer (1662), Holy Communion; spelling modernised, "holy" restored',
    ['creed', 'confession-of-faith', 'unison', 'lords-supper'],
  ),

  // ------------------------------------------------------------ prayers
  text(
    'lords-prayer',
    'prayer',
    { en: "The Lord's Prayer", zh: '主祷文' },
    [
      'A: Our Father, who art in heaven,',
      'A: hallowed be thy name.',
      'A: Thy kingdom come,',
      'A: thy will be done',
      'A: on earth, as it is in heaven.',
      'A: Give us this day our daily bread;',
      'A: and forgive us our debts,',
      'A: as we forgive our debtors;',
      'A: and lead us not into temptation,',
      'A: but deliver us from evil.',
      'A: For thine is the kingdom, and the power, and the glory, for ever. Amen.',
    ],
    [
      'A: 我们在天上的父，',
      'A: 愿人都尊你的名为圣。',
      'A: 愿你的国降临；',
      'A: 愿你的旨意行在地上，',
      'A: 如同行在天上。',
      'A: 我们日用的饮食，今日赐给我们。',
      'A: 免我们的债，',
      'A: 如同我们免了人的债。',
      'A: 不叫我们遇见试探；',
      'A: 救我们脱离凶恶。',
      'A: 因为国度、权柄、荣耀，全是你的，直到永远。阿们。',
    ],
    'Matthew 6:9-13 — traditional English form / 和合本 (CUV 1919)',
    ['prayer', 'lords-prayer', 'unison'],
  ),

  text(
    'prayer-for-illumination',
    'prayer',
    { en: 'Prayer for Illumination', zh: '求圣灵光照的祷告' },
    [
      'L: Lord God, your word is a lamp unto our feet, and a light unto our path.',
      'L: As the Scriptures are read and your word is proclaimed, send your Holy Spirit to open our minds and hearts,',
      'L: that, hearing your voice, we may believe and obey, and bear fruit to your glory;',
      'L: through Jesus Christ our Lord.',
      'A: Amen.',
    ],
    [
      'L: 主我们的神，你的话是我们脚前的灯，是我们路上的光。',
      'L: 当圣经被宣读、你的道被传讲的时候，求你差遣圣灵开启我们的心窍，',
      'L: 使我们听见你的声音，就信靠顺服，结出果子，荣耀你的名；',
      'L: 奉主耶稣基督的名。',
      'A: 阿们。',
    ],
    'Canon original (after Psalm 119:105)',
    ['prayer', 'illumination', 'sermon'],
  ),

  text(
    'collect-for-holy-scripture',
    'prayer',
    { en: 'Collect for Holy Scripture', zh: '求主赐我们领受圣经的祷文' },
    [
      'L: Blessed Lord, who hast caused all holy Scriptures to be written for our learning:',
      'L: Grant that we may in such wise hear them, read, mark, learn, and inwardly digest them,',
      'L: that by patience, and comfort of thy holy Word, we may embrace, and ever hold fast the blessed hope of everlasting life,',
      'L: which thou hast given us in our Saviour Jesus Christ.',
      'A: Amen.',
    ],
    [
      'L: 可称颂的主啊，你使一切圣经写成，为要教训我们：',
      'L: 求你赐我们这样听圣经、读圣经、留心、学习，并在心里细细领受，',
      'L: 好叫我们因你圣言所赐的忍耐和安慰，怀抱并永远持守永生的有福盼望，',
      'L: 就是你在我们的救主耶稣基督里所赐给我们的。',
      'A: 阿们。',
    ],
    'Book of Common Prayer (1662), Collect for the Second Sunday in Advent; Chinese tr. Canon (2026)',
    ['prayer', 'illumination', 'scripture', 'advent'],
  ),

  text(
    'offertory-prayer',
    'prayer',
    { en: 'Offertory Sentence and Prayer', zh: '奉献经文与祷告' },
    [
      'L: Thine, O LORD, is the greatness, and the power, and the glory, and the victory, and the majesty: for all that is in the heaven and in the earth is thine; thine is the kingdom, O LORD, and thou art exalted as head above all.',
      'L: All things come of thee, and of thine own have we given thee.',
      '',
      'L: Gracious Father, receive these gifts, which we offer with thankful hearts.',
      'L: Use them for the worship of your name, the work of your church, and the relief of those in need;',
      'L: and with them accept the offering of our lives; through Jesus Christ our Lord.',
      'A: Amen.',
    ],
    [
      'L: 耶和华啊，尊大、能力、荣耀、强胜、威严都是你的；凡天上地下的都是你的；国度也是你的，并且你为至高，为万有之首。',
      'L: 万物都从你而来，我们把从你而得的献给你。',
      '',
      'L: 恩慈的天父，求你悦纳我们存感恩的心所献上的礼物；',
      'L: 使用这些奉献荣耀你的名，推展你教会的事工，并帮助有需要的人；',
      'L: 也求你悦纳我们将自己的生命一同献上。奉主耶稣基督的名。',
      'A: 阿们。',
    ],
    `1 Chronicles 29:11, 14b — ${KJV_CUV}; prayer: Canon original`,
    ['prayer', 'offering'],
  ),

  // ------------------------------------------------------------ the Lord's Supper
  text(
    'lords-supper-invitation',
    'sacrament',
    { en: "Invitation to the Lord's Table", zh: '圣餐的邀请与劝勉' },
    [
      "L: This is the Lord's table. He invites to it all who truly repent of their sins, who trust in Jesus Christ alone for salvation, and who have been baptized and publicly confess faith in him.",
      '',
      'L: Come, not because you are worthy, but because Christ is worthy; not because you are strong, but because you are weak and need his grace.',
      '',
      'L: Yet the apostle warns us: “Let a man examine himself, and so let him eat of that bread, and drink of that cup.”',
      'L: If you are not yet trusting in Christ, or are holding on to sin without repentance, we ask you not to take the bread and the cup, but to pray, and to seek the Lord while he may be found.',
      '',
      'L: Hear the words of our Saviour: “Come unto me, all ye that labour and are heavy laden, and I will give you rest.”',
    ],
    [
      'L: 这是主的筵席。主邀请一切真心为自己的罪悔改、单单信靠耶稣基督得救、已经受洗并公开承认信靠他的人来领受。',
      '',
      'L: 你们来，不是因为自己配得，乃是因为基督配得；不是因为自己刚强，乃是因为自己软弱，需要他的恩典。',
      '',
      'L: 然而使徒提醒我们：“人应当自己省察，然后吃这饼、喝这杯。”',
      'L: 你若还没有信靠基督，或仍持守罪中不肯悔改，请你不要领受饼和杯，乃要祷告，趁主可寻找的时候寻找他。',
      '',
      'L: 请听救主的话：“凡劳苦担重担的人可以到我这里来，我就使你们得安息。”',
    ],
    'Canon original (quoting 1 Corinthians 11:28; Matthew 11:28 — KJV / 和合本)',
    ['lords-supper', 'sacrament', 'fencing'],
  ),

  text(
    'words-of-institution',
    'sacrament',
    { en: 'Words of Institution', zh: '设立圣餐的话' },
    [
      'L: For I have received of the Lord that which also I delivered unto you, That the Lord Jesus the same night in which he was betrayed took bread:',
      'L: And when he had given thanks, he brake it, and said, Take, eat: this is my body, which is broken for you: this do in remembrance of me.',
      '',
      'L: After the same manner also he took the cup, when he had supped, saying, This cup is the new testament in my blood: this do ye, as oft as ye drink it, in remembrance of me.',
      '',
      "L: For as often as ye eat this bread, and drink this cup, ye do shew the Lord's death till he come.",
    ],
    [
      'L: 我当日传给你们的，原是从主领受的，就是主耶稣被卖的那一夜，拿起饼来，',
      'L: 祝谢了，就擘开，说：“这是我的身体，为你们舍的，你们应当如此行，为的是记念我。”',
      '',
      'L: 饭后，也照样拿起杯来，说：“这杯是用我的血所立的新约，你们每逢喝的时候，要如此行，为的是记念我。”',
      '',
      'L: 你们每逢吃这饼，喝这杯，是表明主的死，直等到他来。',
    ],
    `1 Corinthians 11:23-26 — ${KJV_CUV}`,
    ['lords-supper', 'sacrament', 'scripture'],
  ),

  text(
    'communion-thanksgiving-psalm-103',
    'sacrament',
    { en: 'Thanksgiving after Communion: Psalm 103', zh: '圣餐后的感恩：诗篇103篇' },
    [
      'L: Bless the LORD, O my soul:',
      'C: and all that is within me, bless his holy name.',
      'L: Bless the LORD, O my soul,',
      'C: and forget not all his benefits:',
      '',
      'L: Who forgiveth all thine iniquities; who healeth all thy diseases;',
      'C: Who redeemeth thy life from destruction; who crowneth thee with lovingkindness and tender mercies;',
      'L: Who satisfieth thy mouth with good things;',
      "C: so that thy youth is renewed like the eagle's.",
    ],
    [
      'L: 我的心哪，你要称颂耶和华！',
      'C: 凡在我里面的，也要称颂他的圣名！',
      'L: 我的心哪，你要称颂耶和华！',
      'C: 不可忘记他的一切恩惠！',
      '',
      'L: 他赦免你的一切罪孽，医治你的一切疾病。',
      'C: 他救赎你的命脱离死亡，以仁爱和慈悲为你的冠冕。',
      'L: 他用美物使你所愿的得以知足，',
      'C: 以致你如鹰返老还童。',
    ],
    `Psalm 103:1-5 — ${KJV_CUV}`,
    ['lords-supper', 'thanksgiving', 'psalm', 'responsive'],
  ),

  // ------------------------------------------------------------ baptism
  text(
    'baptism-institution',
    'sacrament',
    { en: 'Institution and Promise of Baptism', zh: '洗礼的设立与应许' },
    [
      'L: Jesus said: Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:',
      'L: Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world.',
      '',
      'L: Peter said: Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost.',
      'L: For the promise is unto you, and to your children, and to all that are afar off, even as many as the Lord our God shall call.',
    ],
    [
      'L: 耶稣说：所以，你们要去，使万民作我的门徒，奉父、子、圣灵的名给他们施洗。',
      'L: 凡我所吩咐你们的，都教训他们遵守，我就常与你们同在，直到世界的末了。',
      '',
      'L: 彼得说：你们各人要悔改，奉耶稣基督的名受洗，叫你们的罪得赦，就必领受所赐的圣灵；',
      'L: 因为这应许是给你们和你们的儿女，并一切在远方的人，就是主—我们神所召来的。',
    ],
    `Matthew 28:19-20; Acts 2:38-39 — ${KJV_CUV}`,
    ['baptism', 'sacrament', 'scripture', 'covenant'],
  ),

  text(
    'baptism-vows',
    'sacrament',
    { en: 'Baptismal Vows (Children of Believers)', zh: '婴孩洗礼的誓约' },
    [
      'To the parents:',
      'L: Do you believe that your child, like all of us, needs to be washed from sin by the blood of Jesus Christ and made new by the Holy Spirit?',
      'C: We do.',
      'L: Do you trust the promise of God to be a God to believers and to their children, and do you look to Christ alone as your child’s Saviour, as you do for yourselves?',
      'C: We do.',
      'L: Do you promise, depending on the grace of God, to pray for your child, to teach your child the Holy Scriptures and the Christian faith, to live before your child as followers of Christ, and to bring your child to worship with the people of God?',
      'C: We do, God helping us.',
      '',
      'To the congregation:',
      'L: Do you, as members of Christ’s church in this place, promise to welcome this child in love, to pray for him or her, and to help this family bring up this child to know and follow the Lord?',
      'C: We do, God helping us.',
      '',
      'L: N., I baptize you in the name of the Father, and of the Son, and of the Holy Spirit.',
      'A: Amen.',
    ],
    [
      '对父母：',
      'L: 你们是否相信，你们的孩子与我们众人一样，需要耶稣基督的宝血洗净罪孽，并需要圣灵使他/她得以更新？',
      'C: 是的，我们相信。',
      'L: 你们是否信靠神的应许——他要作信徒和信徒儿女的神；并且仰望基督作你们孩子唯一的救主，正如你们仰望他作自己的救主？',
      'C: 是的，我们信靠。',
      'L: 你们是否愿意倚靠神的恩典，承诺为孩子祷告，教导他/她认识圣经和基督教的信仰，在孩子面前活出跟随基督的生命，并带领他/她与神的子民一同敬拜？',
      'C: 是的，求神帮助我们。',
      '',
      '对会众：',
      'L: 你们作为基督在此地教会的肢体，是否愿意以爱心接纳这孩子，为他/她代祷，并帮助这个家庭养育这孩子认识并跟随主？',
      'C: 是的，求神帮助我们。',
      '',
      'L: 某某，我奉圣父、圣子、圣灵的名给你施洗。',
      'A: 阿们。',
    ],
    'Canon original (baptismal formula from Matthew 28:19)',
    ['baptism', 'sacrament', 'vows', 'covenant'],
  ),

  // ------------------------------------------------------------ benedictions
  text(
    'benediction-aaronic',
    'benediction',
    { en: 'Benediction: Numbers 6:24-26', zh: '祝福：民数记6:24-26' },
    [
      'L: The LORD bless thee, and keep thee:',
      'L: The LORD make his face shine upon thee, and be gracious unto thee:',
      'L: The LORD lift up his countenance upon thee, and give thee peace.',
      'C: Amen.',
    ],
    ['L: 愿耶和华赐福给你，保护你。', 'L: 愿耶和华使他的脸光照你，赐恩给你。', 'L: 愿耶和华向你仰脸，赐你平安。', 'C: 阿们。'],
    `Numbers 6:24-26 — ${KJV_CUV}`,
    ['benediction', 'closing'],
  ),

  text(
    'benediction-apostolic',
    'benediction',
    { en: 'Benediction: 2 Corinthians 13:14', zh: '祝福：哥林多后书13:14' },
    [
      'L: The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all.',
      'C: Amen.',
    ],
    ['L: 愿主耶稣基督的恩惠、神的慈爱、圣灵的感动常与你们众人同在！', 'C: 阿们。'],
    `2 Corinthians 13:14 — ${KJV_CUV}`,
    ['benediction', 'closing', 'trinity'],
  ),

  text(
    'benediction-jude',
    'benediction',
    { en: 'Benediction: Jude 24-25', zh: '祝福：犹大书24-25' },
    [
      'L: Now unto him that is able to keep you from falling, and to present you faultless before the presence of his glory with exceeding joy,',
      'L: To the only wise God our Saviour, be glory and majesty, dominion and power, both now and ever.',
      'C: Amen.',
    ],
    [
      'L: 那能保守你们不失脚、叫你们无瑕无疵、欢欢喜喜站在他荣耀之前的我们的救主—独一的神，',
      'L: 愿荣耀、威严、能力、权柄，因我们的主耶稣基督归与他，从万古以前并现今，直到永永远远。',
      'C: 阿们。',
    ],
    `Jude 24-25 — ${KJV_CUV}`,
    ['benediction', 'closing', 'doxology'],
  ),

  text(
    'benediction-hebrews-13',
    'benediction',
    { en: 'Benediction: Hebrews 13:20-21', zh: '祝福：希伯来书13:20-21' },
    [
      'L: Now the God of peace, that brought again from the dead our Lord Jesus, that great shepherd of the sheep, through the blood of the everlasting covenant,',
      'L: Make you perfect in every good work to do his will, working in you that which is wellpleasing in his sight, through Jesus Christ; to whom be glory for ever and ever.',
      'C: Amen.',
    ],
    [
      'L: 但愿赐平安的神，就是那凭永约之血、使群羊的大牧人—我主耶稣从死里复活的神，',
      'L: 在各样善事上成全你们，叫你们遵行他的旨意；又借着耶稣基督在你们心里行他所喜悦的事。愿荣耀归给他，直到永永远远。',
      'C: 阿们。',
    ],
    `Hebrews 13:20-21 — ${KJV_CUV}`,
    ['benediction', 'closing', 'easter'],
  ),
];
