// The user guide (docs/guide/*.md) inside the app: a table of contents from the headings, a search box that filters
// sections, and the guide in the UI language (en, or zh / zh-Hant — the Traditional file is generated by `npm run i18n`).
import { useEffect, useMemo, useState, type MouseEvent, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { useI18n } from '../i18n.tsx';
import { PageHead, SearchBox, useDebounced } from '../components/ui.tsx';
import { parse, renderBlocks, renderInline, parseInline, sections, stripInline, type RenderOptions, type Section } from '../guide/markdown.ts';
import en from '../../docs/guide/en.md?raw';
import zh from '../../docs/guide/zh.md?raw';
import zhHant from '../../docs/guide/zh-Hant.md?raw';
import './guide.css';

const SOURCES: Record<string, string> = { en, zh, 'zh-Hant': zhHant };

function scrollToId(id: string) {
  const el = document.getElementById(id);
  if (!el) return;
  el.scrollIntoView({ behavior: 'smooth', block: 'start' });
  try {
    history.replaceState(history.state, '', `#${encodeURIComponent(id)}`);
  } catch {
    /* ignore */
  }
}

export default function GuidePage() {
  const { t, lang } = useI18n();
  const src = SOURCES[lang] ?? SOURCES.en;
  const doc = useMemo(() => {
    const blocks = parse(src);
    const title = blocks.find((b) => b.type === 'heading' && b.level === 1);
    return { title: title && title.type === 'heading' ? stripInline(title.text) : t('User guide'), sections: sections(blocks.filter((b) => b !== title)) };
  }, [src, t]);

  const [query, setQuery] = useState('');
  const q = useDebounced(query.trim().toLowerCase(), 150);
  const visible = useMemo(() => (q ? doc.sections.filter((s) => s.haystack.includes(q)) : doc.sections), [doc, q]);
  const [active, setActive] = useState<string | null>(null);
  const [tocOpen, setTocOpen] = useState(false);

  // Jump to the heading in the URL hash once the guide is rendered.
  // (Retried briefly: styles and fonts of the lazily loaded page can still shift the layout after the first paint.)
  useEffect(() => {
    const id = decodeURIComponent(location.hash.slice(1));
    if (!id) return;
    const timers = [0, 150, 500].map((ms) =>
      setTimeout(() => {
        const el = document.getElementById(id);
        if (el && Math.abs(el.getBoundingClientRect().top) > 24) el.scrollIntoView({ block: 'start' });
      }, ms),
    );
    return () => timers.forEach(clearTimeout);
  }, [src]);

  // Highlight the section being read in the table of contents.
  useEffect(() => {
    const els = visible.map((s) => s.heading && document.getElementById(s.heading.id)).filter((e): e is HTMLElement => !!e);
    if (!els.length || typeof IntersectionObserver === 'undefined') return;
    const io = new IntersectionObserver(
      (entries) => {
        const top = entries.filter((e) => e.isIntersecting).sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top)[0];
        if (top) setActive(top.target.id);
      },
      { rootMargin: '0px 0px -70% 0px' },
    );
    els.forEach((e) => io.observe(e));
    return () => io.disconnect();
  }, [visible]);

  const opts: RenderOptions = {
    highlight: q || undefined,
    internalLink: (href, children, key) => <Link key={key} to={href}>{children}</Link>,
    anchorLink: (id, children, key) => (
      <a key={key} href={`#${id}`} onClick={(e: MouseEvent) => { e.preventDefault(); setQuery(''); requestAnimationFrame(() => scrollToId(id)); }}>{children}</a>
    ),
  };

  const tocItems = visible.filter((s): s is Section & { heading: NonNullable<Section['heading']> } => !!s.heading);
  const toc = (
    <nav className="guide-toc-list" aria-label={t('Contents')}>
      {tocItems.map((s) => (
        <a
          key={s.heading.id}
          href={`#${s.heading.id}`}
          className={`lvl${s.heading.level}${active === s.heading.id ? ' active' : ''}`}
          onClick={(e) => { e.preventDefault(); setTocOpen(false); scrollToId(s.heading.id); }}
        >
          {renderInline(parseInline(stripInline(s.heading.text)), {}, s.heading.id)}
        </a>
      ))}
    </nav>
  );

  let lastParent: string | null = null;
  const body: ReactNode[] = visible.map((s, i) => {
    // In search results, show the chapter an h3 belongs to when its h2 is not itself listed.
    const showParent = !!q && s.parent && s.parent !== lastParent && !visible.some((v) => v.heading?.level === 2 && v.heading.text === s.parent);
    if (s.heading?.level === 2) lastParent = s.heading.text;
    else if (s.parent) lastParent = s.parent;
    return (
      <section key={s.heading?.id ?? `intro-${i}`} className="guide-section">
        {showParent && <div className="eyebrow">{stripInline(s.parent!)}</div>}
        {renderBlocks(s.heading ? [s.heading, ...s.blocks] : s.blocks, opts, `s${i}`)}
      </section>
    );
  });

  return (
    <div className="page guide-page">
      <PageHead eyebrow={t('Help')} title={doc.title} sub={t('The weekly routine, step by step: plan the service, roster, bulletin, slides and more.')} />
      <div className="guide">
        <aside className="guide-toc">
          <SearchBox value={query} onChange={setQuery} placeholder={t('Search the guide…')} />
          {q && (
            <div className="small muted guide-count">
              {visible.length ? t('{n} sections match').replace('{n}', String(visible.length)) : null}
            </div>
          )}
          <details className="guide-toc-mobile" open={tocOpen} onToggle={(e) => setTocOpen((e.target as HTMLDetailsElement).open)}>
            <summary>{t('Contents')}</summary>
            {toc}
          </details>
          <div className="guide-toc-desktop">
            <div className="eyebrow">{t('Contents')}</div>
            {toc}
          </div>
        </aside>
        <article className="card guide-body">
          {visible.length ? body : (
            <div className="stack" style={{ alignItems: 'flex-start' }}>
              <p className="muted">{t('No sections match “{q}”.').replace('{q}', query.trim())}</p>
              <button className="btn" onClick={() => setQuery('')}>{t('Clear search')}</button>
            </div>
          )}
        </article>
      </div>
    </div>
  );
}
