// GENERATED by `npm run i18n` from locales/<code>/ — do not edit. See CONTRIBUTING-TRANSLATIONS.md.
/** Languages with an interface translation (a locales/<code>/ui.json), English first. */
export const UI_LOCALES: string[] = ["en","zh","zh-Hant"];
/** How much of the interface each language has (0–1). */
export const UI_COVERAGE: Record<string, number> = {"en":1,"zh":1,"zh-Hant":1};
/** For a phrase a language lacks: this language next, then English. */
export const UI_FALLBACK: Record<string, string> = {"zh-Hant":"zh","zh":"zh-Hant"};
