// Generate the Traditional Chinese UI dictionary from the Simplified one (OpenCC, Taiwan phrasing).
// Runs automatically before `npm run build`; run `npm run i18n` after editing src/i18n/*.ts or docs/guide/zh.md.
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import * as OpenCC from 'opencc-js';

const dir = path.resolve(import.meta.dirname, '../src/i18n');
const s2t = OpenCC.Converter({ from: 'cn', to: 'tw' });
const merged: Record<string, string> = {};
for (const f of fs.readdirSync(dir).filter((f) => f.endsWith('.ts') && !f.includes('generated'))) {
  const mod = (await import(pathToFileURL(path.join(dir, f)).href)) as { default: Record<string, string> };
  Object.assign(merged, mod.default);
}
const out = Object.fromEntries(Object.entries(merged).map(([k, v]) => [k, s2t(v)]));
fs.writeFileSync(
  path.join(dir, 'zh-Hant.generated.ts'),
  `// GENERATED by scripts/gen-i18n-hant.ts from the Simplified Chinese dictionaries. Do not edit.\nconst zhHant: Record<string, string> = ${JSON.stringify(out, null, 1)};\nexport default zhHant;\n`,
);
console.log(`zh-Hant UI dictionary: ${Object.keys(out).length} strings`);

// The in-app user guide (src/pages/Guide.tsx): Traditional Chinese is generated from docs/guide/zh.md the same way.
const guideDir = path.resolve(import.meta.dirname, '../docs/guide');
if (fs.existsSync(path.join(guideDir, 'zh.md'))) {
  const md = s2t(fs.readFileSync(path.join(guideDir, 'zh.md'), 'utf8'));
  fs.writeFileSync(path.join(guideDir, 'zh-Hant.md'), `<!-- GENERATED by scripts/gen-i18n-hant.ts from docs/guide/zh.md. Do not edit. -->\n${md}`);
  console.log('zh-Hant user guide: docs/guide/zh-Hant.md');
}
